### ISSUE TITLE
Fetching Prices / Websocket

### ISSUE THREAD

**Issue by kaleb-keny** [pyth-network/pyth-js#64]
Hey @ali-bahjati  I'm trying to setup a socket that listens to the price updates as done in [here](https://github.com/pyth-network/pyth-js/blob/main/pyth-evm-js/src/examples/EvmRelay.ts)
So the endpoint is `https://xc-mainnet.pyth.network/` shouldn't it be `ws://xc-mainnet.pyth.network/` or `ws://xc-mainnet.pyth.network/`. Other than that, once i connect to that end point, can you tell me what does the rpc payload look for subscribing, methods and params please (using ETH feed as an example `0xca80ba6dc32e08d06f1aa886011eed1d77c77be9eb761cc10d72b7d0a2fd57a6`)?

**Comment by ali-bahjati** [comment]
Hi @kaleb-keny,

PriceServiceConnection converts the endpoint within itself and you should pass the http url (as stated in the example).

If you are implementing it in another language, `wss://xc-mainnet.pyth.network/ws` is the web socket URL. And [this](https://github.com/pyth-network/pyth-js/blob/main/pyth-common-js/src/PriceServiceConnection.ts#L27) is the payload structure.

**Comment by kaleb-keny** [comment]
thanks @ali-bahjati 
```
import websockets
import asyncio
import json
import nest_asyncio
nest_asyncio.apply()

socket  = 'wss://xc-mainnet.pyth.network/ws'
payload = json.dumps({'type':'subscribe','ids':['ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace'],'verbose':True})

async def subscribe():
    async with websockets.connect(socket) as ws:
        await ws.send(payload)
        result = await ws.recv()
        print(result)
        async for message in ws:
            print(message)

#%%
if __name__ == '__main__':    
    loop  = asyncio.get_event_loop()        
    group = asyncio.gather(*[subscribe()],return_exceptions=True)
    loop.run_until_complete(group)
```
If someone comes across it one day out there, you're welcome
